<?php
    session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>View Session Variables</title>

    <link rel="stylesheet" href="node_modules/bulma/css/bulma.css">
</head>
<body class="container">
    <div class="content">
        <?php
            echo "<h2>Session Name: " . $_SESSION["name"] . "</h2>";
            echo "<h2>Session Email: " . $_SESSION["email"] . "</h2>";
        ?>
    </div>
</body>
</html>